const arabic = {
    home: "الرئيسية",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    wishlist: "المفضله",
    Products: "المنتجات",
    Categories: "الاقسام",
    Brands: "الماركات",
    search: "ما الذي تبحث عنه",
    add: "الاضافه",
    firstName: "الاسم الاول",
    emailAdress: "البريد الالكتروني",
    password: "كلمه المرور",
    confirmPassword: " تأكيد كلمه المرور",
    phoneNumber: "رقم الهاتف",
    submit: "ارسال",
    registerNow: " انشاء حساب ",
    forgetPassword: " نسيت كلمه المرور",
    registerMS: "هل لديك حساب؟",
    next: "التالي",
    previous: "السابق",
    page: "صفحه",
    of: "من",
    FilterbyCategory: "التصفية حسب الفئة",
    AllCategories: "كل الفئات",
    MinPrice: "الحد الادني",
    MaxPrice: "الحد الاقصي",
    AllBrands: "كل الماركات",
    Productsby: "المنتجات حسب",
    ProductsIn: "المنتجات في",
    CartItems: "عناصر العربه",
    Noproductsinyourcart: "لا توجد منتجات في عربتك",
    Checkout: "الدفع",
    Clearcart: "مسح العربه",
    Logout: "تسجيل الخروج",
    Noproductsfoundforthisbrand: "لم يتم العثور علي منتجات لهذه الماركه",
    Noproductsfound: "لم يتم العثور علي منتجات",
    Subtotal: "المجموع الفرعي",
    Shipping: "الشحن",
    Total: "المجموع",
    Admin: "المشرف",
    HelloAdmin: "مرحبا بالمشرف",
    ProductManager: "مدير المنتجات",
    ProductName: "اسم المنتج",
    Category: "الفئة",
    Image: "الصورة",
    Price: "السعر",
    allFav:"كل منتجاتك المفضله"



}
export default arabic