const english = {
    home: "Home",
    signIn: "Sign In",
    signUp: "Sign Up",
    wishlist: "wishlist",
    Products: "Products",
    Categories: "Categories",
    Brands : "Brands",
    search : " What are you looking for",
    add: "Add to Cart",
    firstName: "First name",
    emailAdress: "Email address", 
    password : "Password",
    confirmPassword: "Confirm Password",
    phoneNumber: "Phone Number",
    submit : "Submit",
    registerNow: "Register Now ",
    forgetPassword: "Forget Password",
    registerMS: "Don't have an account?",
    next: "Next",  
    previous: "Previous",
    page: "Page", 
    of: "of",
}
export default english