const english = {
    home: "Home",
    signIn: "Sign In",
    signUp: "Sign Up",
    wishlist: "wishlist",
    Products: "Products",
    Categories: "Categories",
    Brands: "Brands",
    search: " What are you looking for",
    add: "Add ",
    firstName: "First name",
    emailAdress: "Email address",
    password: "Password",
    confirmPassword: "Confirm Password",
    phoneNumber: "Phone Number",
    submit: "Submit",
    registerNow: "Register Now ",
    forgetPassword: "Forget Password",
    registerMS: "Don't have an account?",
    next: "Next",
    previous: "Previous",
    page: "Page",
    of: "of",
    FilterbyCategory: "Filter by Category",
    AllCategories: "All Categories",
    MinPrice: "Min Price",
    MaxPrice: "Max Price",
    AllCategories: "All Categories",
    AllBrands: "All Brands",
    Productsby: "Products by",
    ProductsIn: "Products in",
    CartItems: "Cart Items",
    Noproductsinyourcart: "No products in your cart",
    Checkout: "Checkout",
    Logout: "Logout",
    Noproductsfoundforthisbrand: "No products found for this brand",
    Noproductsfound: "No products found",
    Clearcart: "Clear cart",
    Subtotal: "Subtotal",
    shipping: "Shipping",
    Total: "Total",
}
export default english